### PR TITLE
Fix train_model.py bug, fix Analysis module import

### PR DESCRIPTION
**Pull request by smericks**
- Fix bug for params_as_inputs in train_model.py
- Fix relative import in train_model.py
- Fix import of Analysis module in __init__.py

### CODE REVIEW

**Comment by smericks** [comment]
@swagnercarena I tried to reproduce the failed test (test_plot_coverage() in analysis tests), but I'm passing all tests on my machine. Any idea what's causing this?

**Review by JelleAalbers — COMMENTED** [review]
Looks good Sydney, thanks for fixing! Maybe you'd like to do `if params_as_inputs` instead of `if len(params_as_inputs) > 0`; that's slightly more concise and also catches values like None or False (don't see how those could easily arise in this code though).

I saw the same test failure; I think it is due to a new matplotlib version. So we'd see the same on  master if we were to redo the build there. https://github.com/swagnercarena/paltas/pull/38, and in particular https://github.com/swagnercarena/paltas/pull/38/commits/94bfd3d83c8d3bf650dc53ffbcf093224edbcdd2, will fix this.

**Comment by smericks** [comment]
Yes I agree that's a cleaner way to do it, I just made that change. 

Ok I see, glad there's a fix on the way!

**Review by JelleAalbers — APPROVED** [review]
Thanks Sydney!

**Comment by JelleAalbers** [comment]
@swagnercarena Do you agree this is good to merge? Sorry, I should have asked you explicitly before approving.

**Comment by swagnercarena** [comment]
Thanks for making these additions @smericks. I went ahead and included @JelleAalbers fix so that we didn't get failures on the main page (I also included a 0.1 decrease coverage threshold for failure since the 0% threshold was too strict).

**Pull request merged**
