### PR TITLE
fix calls to lenstronomy for new version

### PR DESCRIPTION
**Pull request by smericks**
- PointSource() now takes in 'lens_model' instead of 'lensModel' as a kwarg (change to config_handler.py)
- remove use of a private function in MainDeflector.simple_deflectors.py

### CODE REVIEW

**Comment by sibirrer** [comment]
@swagnercarena this PR should be merged ASAP to guarantee consistency with lenstronomy. I think the issue with the test failing is that paltas required an older version of lenstronomy

**Review by swagnercarena — DISMISSED** [review]

**Comment by swagnercarena** [comment]
@smericks, can you modify the lenstronomy requirements to the new pip version with this change? That should also trigger the tests to run again.

**Comment by smericks** [comment]
@swagnercarena @sibirrer So the switch from_import_class() to lens_class() happened Oct 27th (https://github.com/lenstronomy/lenstronomy/commit/f815d0694dd55b3afc224cb30cd3f226515090c5)

But the latest pip version of lenstronomy is from Sep 28th (https://github.com/lenstronomy/lenstronomy/releases/tag/v1.11.5)

So I don't think this change is compatible with a pip release of lenstronomy yet. Since I'm working with more up to date lenstronomy than the pip release, I tried to jump the gun on changing this.

**Comment by swagnercarena** [comment]
Okay, let's circle back to this pull request once the newest pip version of lenstronomy is compatible with the change. Thanks @smericks!

**Comment by sibirrer** [comment]
> Okay, let's circle back to this pull request once the newest pip version of lenstronomy is compatible with the change. Thanks @smericks!

ah, I see. On my way for a new lenstronomy release and then ping here. Thank you!

**Comment by sibirrer** [comment]
@smericks @swagnercarena lenstronomy version 1.11.6 is available on pip

**Review by swagnercarena — APPROVED** [review]

**Pull request merged**
